using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using uniBuddyAPI.Models;
using uniBuddyAPI.Services;
using System.Linq;

namespace uniBuddyAPI.Controllers
{
    [ApiController]
    [Route("calendar")]
    [Produces("application/json")]
    public class CalendarController : Controller
    {
        private readonly RealTimeDbService _db;
        public CalendarController(RealTimeDbService db)
        {
            _db = db;
        }

        [HttpPost("{userId}")] //adding a calendar event
        public async Task<IActionResult> AddEvent(string userId, [FromBody] CalendarEvent body)
        {
            if (string.IsNullOrWhiteSpace(userId))
                return BadRequest(new { message = "The userId is required" });

            if (body == null || string.IsNullOrWhiteSpace(body.Title))
                return BadRequest(new { message = "Title is required" });

            var evnt = new CalendarEvent
            {
                //EventId generated by Firebase on POST
                UserId = userId,
                Title = body.Title,
                Location = body.Location,
                CourseId = body.CourseId,
                Notes = body.Notes,
                EventDate = body.EventDate?.Trim() //"yyyy-MM-dd"
            };

            var response = await _db.Client.PostAsJsonAsync($"/calendar-events/{userId}.json", evnt);

            if (response.IsSuccessStatusCode)
            {
                var resultContent = await response.Content.ReadAsStringAsync();
                return Ok(new { message = "Event saved successfully", data = resultContent });
            }
            return BadRequest(new { message = "Failed to save your event" });
        }

        [HttpGet("{userId}")] //getting the logged-in user's events
        public async Task<IActionResult> GetEvents(string userId, [FromQuery] string? courseId = null)
        {
            if (string.IsNullOrWhiteSpace(userId))
                return BadRequest(new { message = "The userId is required" });

            var response = await _db.Client.GetAsync($"/calendar-events/{userId}.json");
            if (!response.IsSuccessStatusCode)
                return BadRequest(new { message = "Could not load events" });

            var json = await response.Content.ReadAsStringAsync();
            if (string.IsNullOrWhiteSpace(json) || json == "null")
                return NotFound(new { message = "you have no events saved yet" });

            Dictionary<string, CalendarEvent>? map;
            try
            {
                //Code Attribution
                //The PropertyNameCaseInsensitive option has been created with the help of StackOverflow
                //https://stackoverflow.com/questions/45782127/json-net-case-insensitive-deserialization-not-working
                //Ziaullah Khan
                //https://stackoverflow.com/users/3312570/ziaullah-khan
                map = JsonSerializer.Deserialize<Dictionary<string, CalendarEvent>>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });
            }
            catch
            {
                return Ok(new List<CalendarEvent>()); //keep app safe from crash
            }

            var list = new List<CalendarEvent>();
            if (map != null)
            {
                foreach (var entry in map)
                {
                    entry.Value.EventId = entry.Key; //firebase key as event id
                    entry.Value.UserId = userId;
                    list.Add(entry.Value);
                }
            }

            if (!string.IsNullOrWhiteSpace(courseId))
            {
                list = list
                    .Where(e => string.Equals(e.CourseId, courseId, StringComparison.OrdinalIgnoreCase))
                    .ToList();
            }

            return Ok(list);
        }

        [HttpDelete("{userId}/{eventId}")] //deleting a specific event
        public async Task<IActionResult> DeleteEvent(string userId, string eventId)
        {
            if (string.IsNullOrWhiteSpace(userId) || string.IsNullOrWhiteSpace(eventId))
                return BadRequest(new { message = "userId and eventId are required" });

            var response = await _db.Client.DeleteAsync($"/calendar-events/{userId}/{eventId}.json");

            if (response.IsSuccessStatusCode)
                return Ok(new { message = "Event deleted" });

            return BadRequest(new { message = "Could not delete event" });
        }

        [HttpGet("global")] //read-only global (preloaded) events
        public async Task<IActionResult> GetGlobalEvents([FromQuery] string? courseId = null)
        {
            var response = await _db.Client.GetAsync("/calendar-global.json");
            if (!response.IsSuccessStatusCode) return BadRequest(new { message = "Could not load global events" });

            var json = await response.Content.ReadAsStringAsync();
            if (string.IsNullOrWhiteSpace(json) || json == "null") return Ok(new List<CalendarEvent>());

            Dictionary<string, CalendarEvent>? map;
            try
            {
                map = JsonSerializer.Deserialize<Dictionary<string, CalendarEvent>>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });
            }
            catch
            {
                return Ok(new List<CalendarEvent>());
            }

            var list = new List<CalendarEvent>();
            if (map != null)
            {
                foreach (var entry in map)
                {
                    entry.Value.EventId = entry.Key; //Firebase key
                    //UserId stays null for global
                    list.Add(entry.Value);
                }
            }

            if (!string.IsNullOrWhiteSpace(courseId))
                list = list.Where(e => string.Equals(e.CourseId, courseId, StringComparison.OrdinalIgnoreCase)).ToList();
            return Ok(list);
        }
    }
}
